
#                           Important

TOKEN : YOUR_TOKEN     # Replace "YOUR_TOKEN" With your Token
CHANNELID : 123        # Replace "123" With your Channel ID
LANGUAGE : ar          # Languages ar = Arabic, en = English, for custom Message Type "custom"
TIME : 120             # Time with seconds 120s = 2m
CONTANT : ""           # Custom message contant
DEL : false            # Make it True to deleting the messages after 5 seconds of sending it